[tool.poetry]
name = "bookie-backend"
version = "0.1.0"
description = "The API Backend for bookie"
authors = ["charitarthchugh <37895518+charitarthchugh@users.noreply.git>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
black = { extras = ["d"], version = "^22.3.0" }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
