name: Format Code

on:
  push:
    branches:
      - develop

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Format Files with Prettier
        uses: actionsx/prettier@v2
        with:
          args: -w frontend/
      - name: Get Changed Files 
        id: changed-files
        uses: tj-actions/changed-files@v18.7
      - name: Commit Files
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{github.token}}
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          commit-message: Format Files with Prettier
          ref: refs/head/develop
