name: Format Code
on:
  push:
    branches:
      - develop*
jobs:
  flutter:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
      - name: Format Files with flutter format
        run: flutter format .
      - id: changed-files
        name: Get changed files
        uses: tj-actions/changed-files@v24.1
        with:
          separator: '\n'
      - if: steps.changed-files-specific.outputs.any_modified == 'true'
        name: Commit-back changes
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{steps.changes.outputs.all_modified_files}}
          commit-message:  "style(backend): format files with flutter"
  python:
    defaults:
      run:
        working-directory: ./backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Black format
        uses: psf/black@stable
        with:
          options: --verbose
      - name: Run isort format
        uses: isort/isort-action@master
        with:
          configuration: --profile black
      - id: changed-files
        name: Get changed files
        uses: tj-actions/changed-files@v24.1
        with:
          separator: '\n'
      - if: steps.changed-files-specific.outputs.any_modified == 'true'
        name: Commit-back changes
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{steps.changes.outputs.all_modified_files}}
          commit-message: "style(backend): format files with isort and black"
