name: Format Code
on:
  push:
    branches:
      - develop*

jobs:
  flutter:
    defaults:
      run:
        working-directory: ./frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1
      - name: Format Files with flutter format
        run: flutter format .
      - id: changes
        name: Get changed files
        uses: tj-actions/verify-changed-files@v8.8
        with:
          separator: \n
      - if: steps.changes.outputs.changed_files != ''
        name: Commit-back changes
        uses: actions-x/commit@v5
        with:
          message: "style(backend): format files with flutter"
          name: github-actions
  python:
    defaults:
      run:
        working-directory: ./blackend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Black format
        uses: psf/black@stable
        with:
          options: --verbose
      - name: Run isort format
        uses: isort/isort-action@master
        with:
          configuration: --profile black
      - id: changed-files
        name: Get changed files
        uses: tj-actions/changed-files@v18.7
        with:
          files: "*.py\n"
      - if: steps.changed-files.outputs.any_changed == 'true'
        name: Commit
        uses: actions-x/commit@v5
        with:
          message: "style(backend): format files with isort and black"
          name: github-actions
