name: Format Code

on:
  push:
    branches:
      - develop

jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Format Files with Prettier
        uses: actionsx/prettier@v2
        with:
          args: -w frontend/
      - name: 'Get changed files'
        id: changes
        uses: tj-actions/verify-changed-files@v8.8
        with:
          separator: '\n'
      - name: 'Commit-back changes'
        if: steps.changes.outputs.changed_files != ''
        uses: swinton/commit@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.changes.outputs.changed_files }}
          commit-message: 'Format files with Prettier'
          ref: ${{ github.head_ref }}
